### ISSUE TITLE
Using WebSocket from an iframe

### ISSUE THREAD

**Issue by ameshkov** [gorhill/chromium-websocket-wrapper#2]
@gorhill, it seems we have an issue.

I've recently ran into a page tricking us with ease.

Look at this code:

```
var ws = window.WebSocket;
var el = document.createElement('iframe');
el.style.display = 'none';
document.documentElement.appendChild(el);
if (el.contentWindow.WebSocket) {
    ws = el.contentWindow.WebSocket;
    console.log('ba dum tss');
}
```

Frankly, I have no idea how to solve this in a generic way.

**Comment by gorhill** [comment]
@kzar from ABP has a solution for this, see https://github.com/gorhill/uBO-WebSocket/pull/4.

**Comment by ameshkov** [comment]
Oh, nice, thank you @kzar!
